title: Moses Kolleh Sesay
logo: aa2a53a8-d87d-427f-95c4-bbf2feaa2942 Background Removed.png
description: Experienced Environmental Professional with over 2 years in research and water management. Skilled in geospatial analysis (QGIS, ArcGIS, R programming), data analysis (Python, SQL, Tableau, PowerBI), and project management. Contributing to UN disaster risk reduction efforts and leveraging these skills towards sustainable water and climate solutions.
show_downloads: true
theme: jekyll-theme-minimal
